/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformAdminRouteImport } from './routes/platform-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PlatformAdminIndexRouteImport } from './routes/platform-admin/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as PlatformAdminOrganizationsRouteImport } from './routes/platform-admin/organizations'
import { Route as AppTryOnRouteImport } from './routes/_app/try-on'
import { Route as AppTipsRouteImport } from './routes/_app/tips'
import { Route as AppStockRouteImport } from './routes/_app/stock'
import { Route as AppLensRouteImport } from './routes/_app/lens'
import { Route as AppIntakeRouteImport } from './routes/_app/intake'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppPatientsIndexRouteImport } from './routes/_app/patients.index'
import { Route as AppPatientsPatientIdRouteImport } from './routes/_app/patients.$patientId'

const PlatformAdminRoute = PlatformAdminRouteImport.update({
  id: '/platform-admin',
  path: '/platform-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminIndexRoute = PlatformAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PlatformAdminOrganizationsRoute =
  PlatformAdminOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => PlatformAdminRoute,
  } as any)
const AppTryOnRoute = AppTryOnRouteImport.update({
  id: '/try-on',
  path: '/try-on',
  getParentRoute: () => AppRoute,
} as any)
const AppTipsRoute = AppTipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppLensRoute = AppLensRouteImport.update({
  id: '/lens',
  path: '/lens',
  getParentRoute: () => AppRoute,
} as any)
const AppIntakeRoute = AppIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIndexRoute = AppPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsPatientIdRoute = AppPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/platform-admin': typeof PlatformAdminRouteWithChildren
  '/import': typeof AppImportRoute
  '/intake': typeof AppIntakeRoute
  '/lens': typeof AppLensRoute
  '/stock': typeof AppStockRoute
  '/tips': typeof AppTipsRoute
  '/try-on': typeof AppTryOnRoute
  '/platform-admin/organizations': typeof PlatformAdminOrganizationsRoute
  '/platform-admin/': typeof PlatformAdminIndexRoute
  '/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/patients/': typeof AppPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/import': typeof AppImportRoute
  '/intake': typeof AppIntakeRoute
  '/lens': typeof AppLensRoute
  '/stock': typeof AppStockRoute
  '/tips': typeof AppTipsRoute
  '/try-on': typeof AppTryOnRoute
  '/platform-admin/organizations': typeof PlatformAdminOrganizationsRoute
  '/': typeof AppIndexRoute
  '/platform-admin': typeof PlatformAdminIndexRoute
  '/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/patients': typeof AppPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/platform-admin': typeof PlatformAdminRouteWithChildren
  '/_app/import': typeof AppImportRoute
  '/_app/intake': typeof AppIntakeRoute
  '/_app/lens': typeof AppLensRoute
  '/_app/stock': typeof AppStockRoute
  '/_app/tips': typeof AppTipsRoute
  '/_app/try-on': typeof AppTryOnRoute
  '/platform-admin/organizations': typeof PlatformAdminOrganizationsRoute
  '/_app/': typeof AppIndexRoute
  '/platform-admin/': typeof PlatformAdminIndexRoute
  '/_app/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/_app/patients/': typeof AppPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/platform-admin'
    | '/import'
    | '/intake'
    | '/lens'
    | '/stock'
    | '/tips'
    | '/try-on'
    | '/platform-admin/organizations'
    | '/platform-admin/'
    | '/patients/$patientId'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/import'
    | '/intake'
    | '/lens'
    | '/stock'
    | '/tips'
    | '/try-on'
    | '/platform-admin/organizations'
    | '/'
    | '/platform-admin'
    | '/patients/$patientId'
    | '/patients'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/platform-admin'
    | '/_app/import'
    | '/_app/intake'
    | '/_app/lens'
    | '/_app/stock'
    | '/_app/tips'
    | '/_app/try-on'
    | '/platform-admin/organizations'
    | '/_app/'
    | '/platform-admin/'
    | '/_app/patients/$patientId'
    | '/_app/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlatformAdminRoute: typeof PlatformAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/platform-admin': {
      id: '/platform-admin'
      path: '/platform-admin'
      fullPath: '/platform-admin'
      preLoaderRoute: typeof PlatformAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-admin/': {
      id: '/platform-admin/'
      path: '/'
      fullPath: '/platform-admin/'
      preLoaderRoute: typeof PlatformAdminIndexRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/platform-admin/organizations': {
      id: '/platform-admin/organizations'
      path: '/organizations'
      fullPath: '/platform-admin/organizations'
      preLoaderRoute: typeof PlatformAdminOrganizationsRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/_app/try-on': {
      id: '/_app/try-on'
      path: '/try-on'
      fullPath: '/try-on'
      preLoaderRoute: typeof AppTryOnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tips': {
      id: '/_app/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof AppTipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock': {
      id: '/_app/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lens': {
      id: '/_app/lens'
      path: '/lens'
      fullPath: '/lens'
      preLoaderRoute: typeof AppLensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intake': {
      id: '/_app/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AppIntakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/': {
      id: '/_app/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AppPatientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId': {
      id: '/_app/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AppPatientsPatientIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppImportRoute: typeof AppImportRoute
  AppIntakeRoute: typeof AppIntakeRoute
  AppLensRoute: typeof AppLensRoute
  AppStockRoute: typeof AppStockRoute
  AppTipsRoute: typeof AppTipsRoute
  AppTryOnRoute: typeof AppTryOnRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPatientsPatientIdRoute: typeof AppPatientsPatientIdRoute
  AppPatientsIndexRoute: typeof AppPatientsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppImportRoute: AppImportRoute,
  AppIntakeRoute: AppIntakeRoute,
  AppLensRoute: AppLensRoute,
  AppStockRoute: AppStockRoute,
  AppTipsRoute: AppTipsRoute,
  AppTryOnRoute: AppTryOnRoute,
  AppIndexRoute: AppIndexRoute,
  AppPatientsPatientIdRoute: AppPatientsPatientIdRoute,
  AppPatientsIndexRoute: AppPatientsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PlatformAdminRouteChildren {
  PlatformAdminOrganizationsRoute: typeof PlatformAdminOrganizationsRoute
  PlatformAdminIndexRoute: typeof PlatformAdminIndexRoute
}

const PlatformAdminRouteChildren: PlatformAdminRouteChildren = {
  PlatformAdminOrganizationsRoute: PlatformAdminOrganizationsRoute,
  PlatformAdminIndexRoute: PlatformAdminIndexRoute,
}

const PlatformAdminRouteWithChildren = PlatformAdminRoute._addFileChildren(
  PlatformAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PlatformAdminRoute: PlatformAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
